# 社交登录配置文件 (Prod)

spring:
  config:
    activate:
      on-profile: prod

wx:
  # 微信小程序配置
  ma:
    app-id: ${prod.wx.ma.appId}
    app-secret: ${prod.wx.ma.appSecret}
  # 微信 App 配置 (Flutter)
  app:
    app-id: ${prod.wx.app.appId}
    app-secret: ${prod.wx.app.appSecret}

# Apple 登录配置
apple:
  client-id: ${prod.apple.clientId}
