server:
  port: 8086

spring:
  application:
    name: mallchat-chat-service
  profiles:
    active: default
  config:
    activate:
      on-profile: default
    import:
      - nacos:common-secret.properties?group=DEFAULT_GROUP&refresh=true
      - nacos:common-web.yml?group=DEFAULT_GROUP&refresh=true
      - nacos:common-cache.yml?group=DEFAULT_GROUP&refresh=true
      - nacos:common-mysql.yml?group=DEFAULT_GROUP&refresh=true
      - nacos:common-rabbitmq.yml?group=DEFAULT_GROUP&refresh=true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: mallchat-cloud
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
      config:
        server-addr: localhost:8848
        namespace: mallchat-cloud
        group: DEFAULT_GROUP
        file-extension: yml
        username: nacos
        password: nacos

# MyBatis-Plus 业务配置
mybatis-plus:
  type-aliases-package: com.stephen.cloud.chat.model.entity
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
